spring.application.name=organiza-ai

# Configuração de Fonte de Dados (Banco de Dados)
spring.datasource.url=jdbc:mysql://localhost:3306/organiza_ai
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
