spring.application.name=organiza-ai

# Configuração de Fonte de Dados (Banco de Dados)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Para você visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console